//Ładowanie grafik
div = document.createElement("DIV");
image = document.getElementById("ladowanieZdjecie");
div.style.backgroundImage = "url('Obrazy/Ładowanie.png')";
div.style.backgroundPosition = "center";
div.style.backgroundRepeat = "no-repeat";
div.style.backgroundSize = "cover";
div.style.zIndex = "10";
div.className = "wyborNicku";
div.id = "ladowanie";
document.body.appendChild(div);
setInterval(function(){ image.style.backgroundImage = "url('Obrazy/Mapa/Mapa.png')"; }, 1);
setInterval(function(){ image.style.backgroundImage = "url('Obrazy/Mapa/PradawnyLas.png')"; }, 2);
setInterval(function(){ image.style.backgroundImage = "url('Obrazy/Mapa/ZrujnowanyObóz.png')"; }, 3);
setInterval(function(){ image.style.backgroundImage = "url('Obrazy/Tła/Grota.png')"; }, 4);
setInterval(function(){ image.style.backgroundImage = "url('Obrazy/Tła/GrzybowePole.png')"; }, 5);
setInterval(function(){ image.style.backgroundImage = "url('Obrazy/Tła/PradawnyLas.png')"; }, 6);
setInterval(function(){ image.style.backgroundImage = "url('Obrazy/Tła/WieżaMaga.png')"; }, 7);
setInterval(function(){ image.style.backgroundImage = "url('Obrazy/Tła/ZrujnowanyObóz.png')"; }, 8);
setInterval(function(){ image.style.backgroundImage = "url('Obrazy/Przeciwnicy/Drwal.png')"; }, 9);
setInterval(function(){ image.style.backgroundImage = "url('Obrazy/Przeciwnicy/Kowal.png')"; }, 10);
setInterval(function(){ image.style.backgroundImage = "url('Obrazy/Przeciwnicy/Leżące_drzewo.png')"; }, 11);
setInterval(function(){ image.style.backgroundImage = "url('Obrazy/Przeciwnicy/Magiczne_Pole.png')"; }, 12);
setInterval(function(){ image.style.backgroundImage = "url('Obrazy/Przeciwnicy/Grzybiarz.png')"; }, 13);
setInterval(function(){ image.style.backgroundImage = "url('Obrazy/Przeciwnicy/Pułapka.png')"; }, 14);
setInterval(function(){ image.style.backgroundImage = "url('Obrazy/Przeciwnicy/Myśliwy.png')"; }, 15);
setInterval(function(){ image.style.backgroundImage = "url('Obrazy/Przeciwnicy/Młody_myśliwy.png')"; }, 16);
setInterval(function(){ image.style.backgroundImage = "url('Obrazy/Przeciwnicy/Szczurzy_strażnik.png')"; }, 17);
setInterval(function(){ image.style.backgroundImage = "url('Obrazy/Przeciwnicy/Wieśniak.png')"; }, 18);
setInterval(function(){ document.getElementById("ladowanie").setAttribute("hidden", ""); }, 3000);
