//Ładowanie grafik
div = document.createElement("DIV");
image = document.getElementById("ladowanieZdjecie");
div.style.backgroundImage = "url('Obrazy/Ładowanie.png')";
div.style.backgroundPosition = "center";
div.style.backgroundRepeat = "no-repeat";
div.style.backgroundSize = "cover";
div.style.zIndex = "10";
div.className = "wyborNicku";
div.id = "ladowanie";
document.body.appendChild(div);
image.style.backgroundImage = "url('/Obrazy/Mapa/Mapa.png')";
image.style.backgroundImage = "url('/Obrazy/Mapa/PradawnyLas.png')";
image.style.backgroundImage = "url('/Obrazy/Mapa/ZrujnowanyObóz.png')";
image.style.backgroundImage = "url('/Obrazy/Tła/Grota.png')";
image.style.backgroundImage = "url('/Obrazy/Tła/GrzybowePole.png')";
image.style.backgroundImage = "url('/Obrazy/Tła/PradawnyLas.png')";
image.style.backgroundImage = "url('/Obrazy/Tła/WieżaMaga.png')";
image.style.backgroundImage = "url('/Obrazy/Tła/ZrujnowanyObóz.png')";
image.style.backgroundImage = "url('/Obrazy/Przeciwnicy/Drwal.png')";
image.style.backgroundImage = "url('/Obrazy/Przeciwnicy/Kowal.png')";
image.style.backgroundImage = "url('/Obrazy/Przeciwnicy/Leżące_drzewo.png')";
image.style.backgroundImage = "url('/Obrazy/Przeciwnicy/Magiczne_Pole.png')";
image.style.backgroundImage = "url('/Obrazy/Przeciwnicy/Grzybiarz.png')";
image.style.backgroundImage = "url('/Obrazy/Przeciwnicy/Pułapka.png')";
image.style.backgroundImage = "url('/Obrazy/Przeciwnicy/Myśliwy.png')";
image.style.backgroundImage = "url('/Obrazy/Przeciwnicy/Młody_myśliwy.png')";
image.style.backgroundImage = "url('/Obrazy/Przeciwnicy/Szczurzy_strażnik.png')";
image.style.backgroundImage = "url('/Obrazy/Przeciwnicy/Wieśniak.png')";
setInterval(function(){ document.getElementById("ladowanie").setAttribute("hidden", ""); }, 3000);
